function createfigure(X1, Y1, Z1, S1, C1, X2, Y2, Z2, C2, X3, Y3, Z3, S2, C3)
%CREATEFIGURE(X1, Y1, Z1, S1, C1, X2, Y2, Z2, C2, X3, Y3, Z3, S2, C3)
%  X1:  scatter3 x
%  Y1:  scatter3 y
%  Z1:  scatter3 z
%  S1:  scatter3 s
%  C1:  scatter3 c
%  X2:  scatter3 x
%  Y2:  scatter3 y
%  Z2:  scatter3 z
%  C2:  scatter3 c
%  X3:  scatter3 x
%  Y3:  scatter3 y
%  Z3:  scatter3 z
%  S2:  scatter3 s
%  C3:  scatter3 c

%  Auto-generated by MATLAB on 03-Aug-2015 10:54:37

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,'LineWidth',2,'GridLineStyle','none',...
    'FontWeight','bold',...
    'FontSize',30);
%% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[0 4]);
%% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[0 4]);
%% Uncomment the following line to preserve the Z-limits of the axes
% zlim(axes1,[0 2.5]);
view(axes1,[-37.5 30]);
box(axes1,'on');
grid(axes1,'on');
hold(axes1,'on');

% Create scatter3
scatter3(X1,Y1,Z1,S1,C1,'Marker','.');

% Create scatter3
scatter3(X2,Y2,Z2,S1,C2,'Marker','.');

% Create scatter3
scatter3(X3,Y3,Z3,S2,C3,'Marker','.');

% Create xlabel
xlabel('x ({\mu} m)','FontWeight','bold','FontSize',30);

% Create ylabel
ylabel('y ({\mu} m)','FontWeight','bold','FontSize',30);

% Create zlabel
zlabel('z ({\mu} m)','FontWeight','bold','FontSize',30);

% Create title
title('t=375s','FontWeight','bold','FontSize',30);

